config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :keeps
  root to: "keeps#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keep.rb
class Keep < ApplicationRecord

  validates :name, presence: true, length: { maximum: 50 }
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: { maximum: 50 }
  validates :username, presence: true, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX },
                     uniqueness: { case_sensitive: false }

  has_many :keeps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :email, :password])
  end

  def only_see_own_page
    if current_user.id != params[:id]
      redirect_to root_path, notice: "Sorry, but you are only allowed to view your own profile page."
  end
end
end

app/controllers/keeps_controller.rb
class KeepsController < ApplicationController
  before_action :set_keep, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /keeps
  # GET /keeps.json
  def index
    @keeps = current_user.keeps
  end

  # GET /keeps/1
  # GET /keeps/1.json
  def show
  end

  # GET /keeps/new
  def new
    @keep = current_user.keeps.new
  end

  # GET /keeps/1/edit
  def edit
  end

  # POST /keeps
  # POST /keeps.json
  def create
    @keep = current_user.keeps.new(keep_params)

    respond_to do |format|
      if @keep.save
        format.html { redirect_to @keep, notice: 'Keep was successfully created.' }
        format.json { render :show, status: :created, location: @keep }
      else
        format.html { render :new }
        format.json { render json: @keep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keeps/1
  # PATCH/PUT /keeps/1.json
  def update
    respond_to do |format|
      if @keep.update(keep_params)
        format.html { redirect_to @keep, notice: 'Keep was successfully updated.' }
        format.json { render :show, status: :ok, location: @keep }
      else
        format.html { render :edit }
        format.json { render json: @keep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keeps/1
  # DELETE /keeps/1.json
  def destroy
    @keep.destroy
    respond_to do |format|
      format.html { redirect_to keeps_url, notice: 'Keep was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keep
      @keep = current_user.keeps.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keep_params
      params.require(:keep).permit(:name, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keeps_helper.rb
module KeepsHelper
end

app/views/keeps/_form.html.erb
<%= form_with(model: keep, local: true) do |form| %>
  <% if keep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(keep.errors.count, "error") %> prohibited this keep from being saved:</h2>

      <ul>
      <% keep.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :keep_name %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note, id: :keep_note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/keeps/edit.html.erb
<h1>Editing Keep</h1>

<%= render 'form', keep: @keep %>

<%= link_to 'Show', @keep %> |
<%= link_to 'Back', keeps_path %>

app/views/keeps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Keeps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keeps.each do |keep| %>
      <tr>
        <td><%= keep.name %></td>
        <td><%= keep.note %></td>
        <td><%= link_to 'Show', keep %></td>
        <td><%= link_to 'Edit', edit_keep_path(keep) %></td>
        <td><%= link_to 'Destroy', keep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Keep', new_keep_path %>

app/views/keeps/new.html.erb
<h1>New Keep</h1>

<%= render 'form', keep: @keep %>

<%= link_to 'Back', keeps_path %>

app/views/keeps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @keep.name %>
</p>

<p>
  <strong>Note:</strong>
  <%= @keep.note %>
</p>

<%= link_to 'Edit', edit_keep_path(@keep) %> |
<%= link_to 'Back', keeps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="user_nav">
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
        <%= link_to "Sign out", destroy_user_session_path,:method => 'delete' %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>